import { Injectable } from '@angular/core';
import { IntelligenceProvider } from './intelligence-provider.interface';
import { SupportedLanguage } from '../i18n/i18n.types';
import {
  DocumentAnalysis,
  DocumentSummary,
  DocumentQaAnswer,
  AiProviderConfig
} from '../models/pdf-intelligence.types';

@Injectable({
  providedIn: 'root'
})
export class RemoteAIProvider implements IntelligenceProvider {
  readonly name = 'Remote AI Provider';
  private config: AiProviderConfig = {
    providerName: 'openai',
    userAcceptedDisclosure: false
  };

  setConfig(config: Partial<AiProviderConfig>) {
    this.config = { ...this.config, ...config };
  }

  getConfig(): AiProviderConfig {
    return this.config;
  }

  async isAvailable(): Promise<boolean> {
    return this.config.userAcceptedDisclosure && !!(this.config.apiKey || this.config.endpoint);
  }

  private validatePrerequisites() {
    if (!this.config.userAcceptedDisclosure) {
      throw new Error('AI Privacy Disclosure must be accepted before using remote AI assistance.');
    }
    if (!this.config.apiKey && !this.config.endpoint) {
      throw new Error(
        'Remote AI provider is not configured with an API key or endpoint. Please configure your provider or use 100% Local Mode.'
      );
    }
  }

  async summarize(
    analysis: DocumentAnalysis,
    pageTexts: { pageNumber: number; text: string }[]
  ): Promise<DocumentSummary> {
    this.validatePrerequisites();

    // If configured with endpoint, call remote model
    if (this.config.endpoint) {
      const response = await fetch(this.config.endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(this.config.apiKey ? { 'Authorization': `Bearer ${this.config.apiKey}` } : {})
        },
        body: JSON.stringify({
          task: 'summarize',
          model: this.config.model || 'gpt-4o-mini',
          content: pageTexts.map(p => `[Page ${p.pageNumber}]\n${p.text}`).join('\n\n')
        })
      });

      if (!response.ok) {
        throw new Error(`AI Provider returned HTTP ${response.status}`);
      }

      const data = await response.json();
      return {
        quickSummary: data.quickSummary || data.summary || 'Summary generated by Remote AI.',
        detailedSummary: data.detailedSummary || [data.summary || 'Detailed summary generated by Remote AI.'],
        keyPoints: data.keyPoints || [],
        sectionSummaries: data.sectionSummaries || [],
        modeUsed: 'ai-assisted'
      };
    }

    throw new Error('Remote AI provider is not configured. Please use 100% Local Mode.');
  }

  async extractKeyPoints(
    analysis: DocumentAnalysis,
    pageTexts: { pageNumber: number; text: string }[]
  ): Promise<string[]> {
    this.validatePrerequisites();

    if (this.config.endpoint) {
      const response = await fetch(this.config.endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(this.config.apiKey ? { 'Authorization': `Bearer ${this.config.apiKey}` } : {})
        },
        body: JSON.stringify({
          task: 'extractKeyPoints',
          model: this.config.model || 'gpt-4o-mini',
          content: pageTexts.map(p => `[Page ${p.pageNumber}]\n${p.text}`).join('\n\n')
        })
      });

      if (!response.ok) throw new Error(`AI Provider returned HTTP ${response.status}`);
      const data = await response.json();
      return data.keyPoints || [];
    }

    throw new Error('Remote AI provider is not configured. Please use 100% Local Mode.');
  }

  async translate(text: string, targetLanguage: SupportedLanguage): Promise<string> {
    this.validatePrerequisites();

    if (this.config.endpoint) {
      const response = await fetch(this.config.endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(this.config.apiKey ? { 'Authorization': `Bearer ${this.config.apiKey}` } : {})
        },
        body: JSON.stringify({
          task: 'translate',
          targetLanguage,
          text
        })
      });

      if (!response.ok) throw new Error(`AI Provider returned HTTP ${response.status}`);
      const data = await response.json();
      return data.translatedText || text;
    }

    throw new Error('Remote AI provider is not configured. Please use 100% Local Mode.');
  }

  async answer(
    question: string,
    pageTexts: { pageNumber: number; text: string }[]
  ): Promise<DocumentQaAnswer> {
    this.validatePrerequisites();

    if (this.config.endpoint) {
      const response = await fetch(this.config.endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(this.config.apiKey ? { 'Authorization': `Bearer ${this.config.apiKey}` } : {})
        },
        body: JSON.stringify({
          task: 'answer',
          question,
          context: pageTexts.map(p => `[Page ${p.pageNumber}]\n${p.text}`).join('\n\n')
        })
      });

      if (!response.ok) throw new Error(`AI Provider returned HTTP ${response.status}`);
      const data = await response.json();
      return {
        question,
        answer: data.answer,
        citations: data.citations || [],
        groundedInDocument: true,
        modeUsed: 'ai-assisted'
      };
    }

    throw new Error('Remote AI provider is not configured. Please use 100% Local Mode.');
  }
}
